# Generated by Django 3.1.3 on 2020-12-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201223_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
